#if !canImport(ObjectiveC)
import XCTest

extension PushNotificationsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PushNotificationsTests = [
        ("testInstanceIdShouldNotBeEmptyString", testInstanceIdShouldNotBeEmptyString),
        ("testInterestInTheArrayIsTooLong", testInterestInTheArrayIsTooLong),
        ("testInterestsArrayShouldContainMaximumOf100Interests", testInterestsArrayShouldContainMaximumOf100Interests),
        ("testInterestsArrayShouldNotBeEmpty", testInterestsArrayShouldNotBeEmpty),
        ("testItShouldAuthenticateTheUserSuccessfully", testItShouldAuthenticateTheUserSuccessfully),
        ("testItShouldDeleteTheUserSuccessfully", testItShouldDeleteTheUserSuccessfully),
        ("testItShouldFailToDeleteUserWithEmptyId", testItShouldFailToDeleteUserWithEmptyId),
        ("testItShouldFailToDeleteUserWithIdThatIsTooLong", testItShouldFailToDeleteUserWithIdThatIsTooLong),
        ("testItShouldFailToGenerateTokenWithEmptyId", testItShouldFailToGenerateTokenWithEmptyId),
        ("testItShouldFailToGenerateTokenWithIdThatIsTooLong", testItShouldFailToGenerateTokenWithIdThatIsTooLong),
        ("testPublishToMoreThan1000UsersShouldFail", testPublishToMoreThan1000UsersShouldFail),
        ("testPublishToUsersRequiresAtLeastOneUser", testPublishToUsersRequiresAtLeastOneUser),
        ("testPublishToUsersUsernameShouldBeLessThan165Characters", testPublishToUsersUsernameShouldBeLessThan165Characters),
        ("testPublishToUsersUserShouldNotBeAnEmptyString", testPublishToUsersUserShouldNotBeAnEmptyString),
        ("testSecretKeyShouldNotBeEmptyString", testSecretKeyShouldNotBeEmptyString),
        ("testValidInstance", testValidInstance),
        ("testValidPublishToUsers", testValidPublishToUsers),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PushNotificationsTests.__allTests__PushNotificationsTests),
    ]
}
#endif
